workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      node: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ayden.trackthehill
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Add iOS platform
        script: npx cap add ios
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS
        script: |
          xcodebuild -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath ios/App/App.xcarchive \
            DEVELOPMENT_TEAM=9N38SB2GF2 \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER=TrackTheHill \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            archive
    artifacts:
      - ios/App/App.xcarchive
